name: Auto Comment on Labeled PR

on:
  pull_request:
    types:
      - labeled
      - unlabeled

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository code to the runner.
    - name: Checkout code
      uses: actions/checkout@v3

    # Create a bin directory in the runner's home
    - name: Create bin directory
      run: mkdir -p $HOME/bin

    # Install the latest jq from GitHub releases
    - name: Install jq
      run: |
        jq_latest=$(curl --silent -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/stedolan/jq/releases/latest" | jq -r '.assets[].browser_download_url | select(endswith("jq-linux64"))')
        wget $jq_latest -O $HOME/bin/jq
        chmod +x $HOME/bin/jq

    # Add the bin directory to PATH
    - name: Add bin to PATH
      run: echo "$HOME/bin" >> $GITHUB_PATH

    # Install the latest yq from GitHub releases
    - name: Install yq
      run: |
        yq_latest=$(curl --silent -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/mikefarah/yq/releases/latest" | jq -r '.assets[].browser_download_url | select(endswith("yq_linux_amd64"))')
        wget $yq_latest -O $HOME/bin/yq
        chmod +x $HOME/bin/yq
        
    # Main logic for adding comments based on labels.
    - name: Comment on PR based on external config
      run: |
        # Fetch the labels attached to the PR from the GitHub event JSON.
        pr_labels=$(jq -r '.pull_request.labels[] | .name' "$GITHUB_EVENT_PATH" | tr '\n' ' ')
        
        # Define the path to the external YAML config file.
        config_file=".github/auto-comment-config.yaml"
        
        # Get the number of label-comment mappings defined in the config file.
        num_mappings=$(yq e '.label_mappings | length' "$config_file")
        
        # Loop through each label-comment mapping in the config file.
        for (( i=0; i<$num_mappings; i++ )); do
          # Fetch the labels and comment for the current mapping.
          mapfile -t labels < <(yq e --arg i "$i" '.label_mappings[$i | tonumber].labels[]' "$config_file")
          comment=$(yq e --arg i "$i" '.label_mappings[$i | tonumber].comment' "$config_file")
          
          # Check if all required labels from the current mapping are present in the PR.
          for label in "${labels[@]}"; do
            if [[ ! $pr_labels == *"$label"* ]]; then
              echo "One or more required labels not found. Skipping."
              continue 2  # Skip to the next iteration of the outer loop.
            fi
          done
          
          # If all required labels are found, add the comment to the PR.
          echo "All required labels found. Adding comment."
          gh pr comment "$GITHUB_HEAD_REF" --body "$comment"
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
